package ch.kusar.unittest;

import junit.framework.Assert;

public class SpecialAsserts {

	public void assertThrowsException(
			final Class<? extends Exception> expected,
			final Runnable codeUnderTest) {
		try {
			codeUnderTest.run();
			Assert.fail("Expecting exception but none was thrown.");
		} catch (final Throwable result) {
			if (!expected.isInstance(result)) {
				Assert.fail("Exception was thrown was unexpected.");
			}
		}
	}
}
